version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/${NODE_ENV}/Dockerfile
    restart: always
    ports:
      - "${PORT}:3000"
    links:
      - database
    depends_on:
      - database
    extends:
      file: ./docker/environments.yml
      service: ${NODE_ENV}

  database:
    image: mongo
    restart: always
    ports:
      - "${MONGO}:27017"

  backup:
    image: mongo
    volumes:
      - ./db/backup:/backup
    command: |
      sh -c "mongodump --host database --out /backup/$$(date +'%y-%m-%d_%H-%M-%S')"
    links:
      - database

  restore:
    image: mongo
    volumes:
      - ./db/restore:/restore
    command: |
      mongorestore --host database --drop /restore/
    links:
      - database