version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${DOCKER_NODE_PORT}:3000"
    links:
      - database
    depends_on:
      - database
    

  database:
    image: mongo
    restart: always
    ports:
      - "${DOCKER_MONGO_PORT}:27017"

  backup:
    image: mongo
    volumes:
      - ./db/backup:/backup
    command: |
      sh -c "mongodump --host database --out /backup/$$(date +'%y-%m-%d_%H-%M-%S')"
    links:
      - database

  restore:
    image: mongo
    volumes:
      - ./db/restore:/restore
    command: |
      mongorestore --host database --drop /restore/
    links:
      - database